apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes.fullname" . }}
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.environment }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}